### ISSUE TITLE
Net::SCP failure when db_dump_dir is set

### ISSUE THREAD

**Issue by stevenchanin** [sgruhier/capistrano-db-tasks#109] opened 2017-01-05 16:51 UTC
I keep previous dumps around to allow reloading (e.g. `set :db_local_clean, false`). With version 0.4, the dumps went into my projects `./db` directory. With version 0.6, they were showing up in my project root. So I set `:db_dump_dir` as described in the README:
```
# configure location where the dump file should be created
set :db_dump_dir, "./db"
```

Now when I try to do a db:pull, I get a fatal error:
```
steven$ cap production db:pull
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
ruby-2.3.1
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
Loading local database config
Local database: myproject_development
Please enter answer (Are you sure you want to erase your local database with server database (y)es, (n)o  ? ): y
Loading local database config
Loading remote database config
00:00 db:local:sync
      01 cd /home/deploy/apps/myproject/current && PGPASSWORD='secret_thingy' pg_dump  -U deploy  myproject_production --no-acl --…
    ✔ 01 deploy@myproject.com 0.195s
      02 rm -f ./db/myproject_production_2017-01-05-084704.sql.bz2
    ✔ 02 deploy@myproject.com 0.042s
(Backtrace restricted to imported tasks)
cap aborted!
Net::SCP::Error: SCP did not finish successfully (1): scp: ./db/myproject_production_2017-01-05-084704.sql.bz2: No such file or directory

Tasks: TOP => db:pull => db:local:sync
(See full trace by running task with --trace)
```

**Comment by numbata** [comment] 2017-01-05 16:54
Close this issue due duplicate of #104

**Closed by numbata** 2017-01-05 16:54 UTC

**Comment by stevenchanin** [comment] 2017-01-05 16:56
My bad. Sorry for not looking first.
