### ISSUE TITLE
NoMethodError: undefined method `zone' for Time:Class

### ISSUE THREAD

**Issue by tinynumbers** [sgruhier/capistrano-db-tasks#107] opened 2016-12-14 11:24 UTC
```
$ bundle exec cap --backtrace production app:pull
Loading local database config
Running via Spring preloader in process 92564
Local database     : MyWeb_development
Assets directories : ["public/uploads"]
Please enter answer (Are you sure you want to erase your local database AND your local assets with server database and assets(["public/uploads"]) (y)es, (n)o  ? ): y
Loading local database config
Running via Spring preloader in process 92590
Loading remote database config
cap aborted!
NoMethodError: undefined method `zone' for Time:Class
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/database.rb:44:in `current_time'
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/database.rb:48:in `output_file'
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/database.rb:147:in `db_dump_file_path'
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/database.rb:130:in `clean_dump_if_needed'
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/database.rb:214:in `ensure in remote_to_local'
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/database.rb:214:in `remote_to_local'
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/dbtasks.rb:109:in `block (4 levels) in <top (required)>'
/Users/me/.rvm/gems/ruby-2.3.1@front-porch-2016-website/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/me/.rvm/gems/ruby-2.3.1@front-porch-2016-website/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/me/.rvm/gems/ruby-2.3.1@front-porch-2016-website/gems/sshkit-1.11.4/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
NoMethodError: undefined method `zone' for Time:Class
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/database.rb:44:in `current_time'
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/database.rb:48:in `output_file'
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/database.rb:147:in `db_dump_file_path'
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/database.rb:120:in `dump'
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/database.rb:212:in `remote_to_local'
/Users/me/Documents/GitHub/capistrano-db-tasks/lib/capistrano-db-tasks/dbtasks.rb:109:in `block (4 levels) in <top (required)>'
/Users/me/.rvm/gems/ruby-2.3.1@front-porch-2016-website/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/me/.rvm/gems/ruby-2.3.1@front-porch-2016-website/gems/sshkit-1.11.4/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/me/.rvm/gems/ruby-2.3.1@front-porch-2016-website/gems/sshkit-1.11.4/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => app:pull => app:local:sync
```

Happening in both master HEAD (07290e016) and the published 0.5 version of capistrano-db-tasks.

*versions:*
* ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
* Rails 5.0.0.1
* Capistrano Version: 3.6.1 (Rake Version: 11.3.0)

**Comment by map7** [comment] 2016-12-14 11:35
This is a duplicate of #106

**Comment by numbata** [comment] 2016-12-14 21:16
@tinynumbers close this issue as duplicate of #106

**Closed by numbata** 2016-12-14 21:16 UTC
